# InfiAgentBench Result Notebook

- **Question ID:** 574
- **Concepts:** Comprehensive Data Preprocessing, Correlation Analysis
- **Source file:** `./InfiAgentBench/data/da-dev-tables/tr_eikon_eod_data.csv`
- **Session ID:** `82d50106-8f7c-48a9-b9eb-0a054798b2bc`
- **User ID:** `e2d3d9de-0c57-4dfb-8bd1-5afc2c0c8856`


## Prompt

```text
Question: Perform data preprocessing on the stock prices of Microsoft Corporation (MSFT), SPDR S&P 500 ETF Trust (SPY), and the CBOE Volatility Index (.VIX). This preprocessing includes removing missing values, normalizing the data, and encoding any categorical variables. Calculate the correlation matrix between the preprocessed stock prices.
1. Missing values should be removed entirely from the dataset.
2. The normalization method to be used is feature scaling (rescaling the data to range between 0 and 1).
3. For categorical variables, use one hot encoding method, though no categorical data exists in the provided price columns.
4. The correlation computation method to be used is Pearson's correlation.
```

## Expected Format

```text
@MSFT_SPY_correlation[correlation]
@MSFT_VIX_correlation[correlation]
@SPY_VIX_correlation[correlation]
where "correlation" is a number between -1 and 1, rounded to two decimal places.
```


[STEP GOAL]: Load the dataset and inspect its structure to understand the variables and their types, and also check for any missing values.


In [ ]:
# Load the dataset
file_path = './input/tr_eikon_eod_data.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the dataset
data.head()


In [ ]:
# Check the structure of the dataset
data.info()


In [ ]:
# Check for missing values
data.isnull().sum()



Time consumed: 0.05s
Code output:
Exit Code: 0
Output: 
         Date     AAPL.O  MSFT.O  INTC.O  AMZN.O    GS.N     SPY     .SPX  \
0  2010-01-01        NaN     NaN     NaN     NaN     NaN     NaN      NaN   
1  2010-01-04  30.572827  30.950   20.88  133.90  173.08  113.33  1132.99   
2  2010-01-05  30.625684  30.960   20.87  134.69  176.14  113.63  1136.52   
3  2010-01-06  30.138541  30.770   20.80  132.25  174.26  113.71  1137.14   
4  2010-01-07  30.082827  30.452   20.60  130.00  177.67  114.19  1141.69   

    .VIX    EUR=     XAU=    GDX     GLD  
0    NaN  1.4323  1096.35    NaN     NaN  
1  20.04  1.4411  1120.00  47.71  109.80  
2  19.35  1.4368  1118.65  48.17  109.70  
3  19.16  1.4412  1138.50  49.34  111.51  
4  19.06  1.4318  1131.90  49.10  110.82  
Time consumed: 0.07s
Code output:
Exit Code: 0
Output: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2216 entries, 0 to 2215
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  ---------

The dataset has been successfully loaded. It contains daily closing prices for multiple stocks and indices, including Microsoft Corporation (MSFT.O), SPDR S&P 500 ETF Trust (SPY), and the CBOE Volatility Index (.VIX). The dataset also includes other financial instruments such as Apple Inc. (AAPL.O), Intel Corporation (INTC.O), Amazon.com Inc. (AMZN.O), Goldman Sachs Group Inc. (GS.N), S&P 500 Index (.SPX), EUR/USD exchange rate (EUR=), Gold Spot Price (XAU=), VanEck Vectors Gold Miners ETF (GDX), and SPDR Gold Trust (GLD).

### Key Observations:
1. **Missing Values**: There are missing values in several columns, particularly in the stock price columns.
2. **Data Types**: The 'Date' column is of object type (likely strings), and all other columns are of float64 type.
3. **Categorical Variables**: No categorical variables are present in the dataset.

Next, we will remove the missing values and proceed with the data preprocessing steps.


[STEP GOAL]: Remove missing values from the dataset and select the relevant columns for further preprocessing.


In [ ]:
# Remove rows with missing values
data_cleaned = data.dropna()

# Select the relevant columns
columns_of_interest = ['Date', 'MSFT.O', 'SPY', '.VIX']
data_cleaned = data_cleaned[columns_of_interest]

# Display the first few rows of the cleaned dataset
data_cleaned.head()



Time consumed: 0.05s
Code output:
Exit Code: 0
Output: 
         Date  MSFT.O     SPY   .VIX
1  2010-01-04  30.950  113.33  20.04
2  2010-01-05  30.960  113.63  19.35
3  2010-01-06  30.770  113.71  19.16
4  2010-01-07  30.452  114.19  19.06
5  2010-01-08  30.660  114.57  18.13


[STEP GOAL]: Normalize the selected stock price columns using feature scaling and calculate the correlation matrix using Pearson's correlation.


In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Extract the relevant columns for normalization
stock_prices = data_cleaned[['MSFT.O', 'SPY', '.VIX']]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
normalized_stock_prices = scaler.fit_transform(stock_prices)

# Convert the normalized data back to a DataFrame
normalized_stock_prices_df = pd.DataFrame(normalized_stock_prices, columns=['MSFT.O', 'SPY', '.VIX'], index=data_cleaned.index)

# Display the first few rows of the normalized data
normalized_stock_prices_df.head()


In [ ]:
# Calculate the correlation matrix using Pearson's correlation
correlation_matrix = normalized_stock_prices_df.corr(method='pearson')

# Display the correlation matrix
correlation_matrix



Time consumed: 0.33s
Code output:
Exit Code: 0
Output: 
     MSFT.O       SPY      .VIX
1  0.099899  0.060364  0.280494
2  0.100025  0.061992  0.262738
3  0.097635  0.062425  0.257849
4  0.093634  0.065029  0.255275
5  0.096251  0.067090  0.231343
Time consumed: 0.05s
Code output:
Exit Code: 0
Output: 
          MSFT.O       SPY      .VIX
MSFT.O  1.000000  0.937022 -0.431681
SPY     0.937022  1.000000 -0.576503
.VIX   -0.431681 -0.576503  1.000000


The data preprocessing steps have been completed. Here is a summary of the results:

1. **Missing Values**: Rows with missing values were dropped.
2. **Normalization**: The stock prices for Microsoft Corporation (MSFT.O), SPDR S&P 500 ETF Trust (SPY), and the CBOE Volatility Index (.VIX) were normalized using feature scaling.
3. **Correlation Matrix**: The Pearson correlation matrix was calculated for the normalized stock prices.

### Normalized Stock Prices
The first few rows of the normalized stock prices are:


MSFT.O       SPY      .VIX
1  0.099899  0.060364  0.280494
2  0.100025  0.061992  0.262738
3  0.097635  0.062425  0.257849
4  0.093634  0.065029  0.255275
5  0.096251  0.067090  0.231343


### Correlation Matrix
The Pearson correlation matrix for the normalized stock prices is:


MSFT.O       SPY      .VIX
MSFT.O  1.000000  0.937022 -0.431681
SPY     0.937022  1.000000 -0.576503
.VIX   -0.431681 -0.576503  1.000000


The correlation matrix shows a strong positive correlation between MSFT.O and SPY (0.937), and negative correlations between .VIX and both MSFT.O (-0.432) and SPY (-0.577).


# Summary of Data Preprocessing and Correlation Analysis

### Data Preprocessing Steps:
1. **Loading and Inspecting the Dataset**:
   - The dataset `tr_eikon_eod_data.csv` was loaded and inspected.
   - The dataset contains daily closing prices for multiple stocks and indices, including Microsoft Corporation (MSFT.O), SPDR S&P 500 ETF Trust (SPY), and the CBOE Volatility Index (.VIX).

2. **Handling Missing Values**:
   - Rows with missing values were removed to ensure a clean dataset.

3. **Selecting Relevant Columns**:
   - The columns of interest were selected: `Date`, `MSFT.O`, `SPY`, and `.VIX`.

4. **Normalizing the Data**:
   - The stock prices were normalized using feature scaling (rescaling the data to range between 0 and 1).

### Correlation Analysis:
- The Pearson correlation matrix was calculated for the normalized stock prices.

### Results:
#### Normalized Stock Prices
The first few rows of the normalized stock prices are:


MSFT.O       SPY      .VIX
1  0.099899  0.060364  0.280494
2  0.100025  0.061992  0.262738
3  0.097635  0.062425  0.257849
4  0.093634  0.065029  0.255275
5  0.096251  0.067090  0.231343


#### Correlation Matrix
The Pearson correlation matrix for the normalized stock prices is:


MSFT.O       SPY      .VIX
MSFT.O  1.000000  0.937022 -0.431681
SPY     0.937022  1.000000 -0.576503
.VIX   -0.431681 -0.576503  1.000000


### Interpretation:
- **Positive Correlation**: There is a strong positive correlation between MSFT.O and SPY (0.937), indicating that the stock prices of Microsoft and the S&P 500 ETF move together.
- **Negative Correlation**: There are negative correlations between .VIX and both MSFT.O (-0.432) and SPY (-0.577), suggesting that increases in market volatility (as measured by .VIX) tend to be associated with decreases in the stock prices of Microsoft and the S&P 500 ETF.

This analysis provides insights into the relationships between the stock prices of Microsoft, the S&P 500 ETF, and market volatility.
